### ISSUE TITLE
CSS for FAQ 

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#11]
**CSS:**
Add this:
```
dl {
    font-size: 2.5rem;
    color: white;
    text-align: left;
}
```
_Why?_ We've finally got a chance to use a definition list!

Change this:
```
dt {
    font-size: 25px;
    line-height: 2.5;
    margin-right: 1000px;
    color: white;
}
```
to this:
```
dt {
    line-height: 2.5;
    margin-top: 2.5rem;
    padding: 1rem;
}
```
_Why?_ Some of the formatting went into the entire list, not just the questions. We removed that, and then added margins and padding to put space between each question and the next one.

**Comment by palma4k** [comment]
made changes to css. thank you.
