### ISSUE TITLE
HTML for FAQ

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#12]
Change this:
```
<div>
    <h2>Frequently Asked Qeustions and Answers</h2>
```
to this:
```
    <h2>Frequently Asked Qeustions and Answers</h2>
```
Why? The `<div>` wasn't being used.

Change this:
```
    <dt> Q? When did you started playing? </dt>
    <dt> A. When I was 16 years old.</dt>
```
to this:
```
<dl>
    <dt> Q? When did you started playing? </dt>
    <dd> A. When I was 16 years old.</dd>
```
_Why?_ A definition list needs to start with a `<dl>` and should consist of `<dt>` and `<dd> `containers. We'll use the `<dt>` for questions and `<dd>` for answers.

Change this:
```
<li><video controls="" width="400" height="400">
        <source src="images/guitar.mp4" type="video/mp4"> playing guitar, for fun.</video></li>
```
to this:
```
<div style="float:right"><video controls="" width="400" height="400">
        <source src="images/guitar.mp4" type="video/mp4"> playing guitar, for fun.</video></div>
```
and move it to just above the `<dl>` you added earlier.
_Why?_ 
An `<li>` container can only be in a `<ul>` or `<ol>` and you're not using either one of those on this page.
We're removing the video from inside the FAQs and are going to have it be on the right-hand side of them instead. 

Change this:
```
    <dt> A. No, I also play <strong>Drums</strong>, <strong>guitar</strong> and <strong>Keyboard</strong>.   
    </dt>
```
to this:
```
    <dd> A. No, I also play <strong>Drums</strong>, <strong>guitar</strong> and <strong>Keyboard</strong>.   
    </dd>
```
and change this:
`    <dt>  A. When I first started playing, I would practice about 3 hours a day, for 5 times a week. Now, I practice about an hour 3 times a week.</dt>`
to this:
`    <dd>  A. When I first started playing, I would practice about 3 hours a day, for 5 times a week. Now, I practice about an hour 3 times a week.</dd>`
_Why?_ Questions go in `<dt>` and answers go in `<dd>`.

Change this:
  ```
  <dt>  A. <a href="https://en.wikipedia.org/wiki/Abraham_Laboriel">Abraham laburiel,</a>
       <a href="https://en.wikipedia.org/wiki/Emmanuel_Espinosa">Emmanuel Espinosa,</a>
       <a href="https://en.wikipedia.org/wiki/Victor_Wooten"> Victor Wooten,</a> just to mention the top three influences in the way I play.</dt>
      </div>
```
to this:
```
    <dd>  A. <a href="https://en.wikipedia.org/wiki/Abraham_Laboriel">Abraham laburiel,</a>
       <a href="https://en.wikipedia.org/wiki/Emmanuel_Espinosa">Emmanuel Espinosa,</a>
       <a href="https://en.wikipedia.org/wiki/Victor_Wooten"> Victor Wooten,</a> just to mention the top three influences in the way I play.</dd>
      </dl>
```
_Why?_ Well, answers go into `<dd>`, and since this is the last thing in the Q and A, we have to put a `</dl>` at the bottom to close it.

**Comment by palma4k** [comment]
fixed all errors, thank you.
