### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#13]
**All pages:**
In the navigation, it should be _Frequently asked questions_, not _Frequently ask questions_.

-----

**Site purpose**
Also, what is like to jam or to have jam seessions.
should be
_Also, what is it like to jam or to have jam sessions?_

_Having a place to go on line..._
should be
_This is a place to go online..._

-----

**FAQ**
_When did you started playing?_ 
should be
_When did you start playing?_

**Comment by palma4k** [comment]
Fixed issues, thank you
