### ISSUE TITLE
Image gallery formatting

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#2]
The floats are causing the images to overlap a lot unless the browser window is large. Here's how to address that.

HTML:
1. Move `</main>` to right before `<script>` so it contains the main contents of the page.
2. Remove `style="height: 300px; width: 300px"` from all the images.
3. Move this:
```
<div class="container">
            <span onclick="this.parentElement.style.display='none'" class="closebtn">×</span>
            <img id="expandedImg" style="width:50%" display="center">
            <div id="imgtext"></div>
</div>
```
so it immediately follows this:
```
<div style="text-align:center">
  <h2>Gallery</h2>
  <p>My bass in different positions, click image to enlarge:</p>
</div>
```
4. Remove `style="width:50%"` from this line:
`<img id="expandedImg" style="width:50%" display="center">`

--------------

CSS:
1. Remove this from images.css:
```
img {
    display: block; 
    margin: auto; 
    transform: rotate(90deg); 
}
```

Now add all this:
```
.row {
    margin: 40px 0;
}
.column {
    float: left;
    padding: 10px;
    width: 25%; /* changed from 15% */
}
.column img {
    width: 100%;
    transform: rotate(90deg);
    opacity: .5;
    cursor: pointer;
}
.container {
    position: relative;
    display: center;background-color: rgb(51,51,51,0.8);
    border: rgb(51,51,51,0.2) 20px solid;
    transform: rotate(90deg);
    z-index: 1;
    margin: auto;
}
.container img {
    width: 80%;
}
#imgtext {
    position: absolute;
    right: -20px;
    bottom: 20%;
    color: white;
    background-color: rgb(51,51,51,.8);
    font-size: 20px;
    transform: rotate(270deg);
}
```

This should overlay the lager image on top of the gallery, with a muted background to separate it from the gallery images it's on top of. 

It keeps the proper gallery image proportions so the thumbnails don't look distorted.

Gallery images scale to 1/4 of the screen no matter what the screen size, so they won't overlap any more.

Because we're rotating the images for the container, we have to rotate the container or it won't fit the image. (When the container had no background color it didn't matter, but now it does.)

Because the container is rotated, we have to rotate the caption as well, or it'll be sideways.

Because of the rotation, the positioning is off: "right" is really bottom, and "bottom" is really left. Confusing, huh? That's why I usually try to edit images to the rotation I want, so I don't have to fight with a web browser!

**Comment by palma4k** [comment]
make sense with the images be at the right rotation before loading it onto the browser (web), thank you.
