### ISSUE TITLE
Navigation HTML change for all pages

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#6]
Change 
```
<nav>
  <ul>
      <ul>
```
to
```
<nav>
  <ul>
```
_Why?_ Because you don't need a `<ul>` inside a `<ul>`. It's not valid HTML.

Change
```
    </ul>
  </ul>
</nav>
```
to
```
  </ul>
</nav>
```
_Why?_ We got rid of an opening `<ul>` so we have to get rid of the corresponding closing `</ul>`.

**Comment by palma4k** [comment]
cleared mistakes, it's so easy to over look those little things. thanks.
