### ISSUE TITLE
HTML and CSS changes for Site Purpose

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#7]
Delete <`title>LetsJam.com</title>` from the `<header>`. 
_Why?_ Titles belong in the `<head>`, no the `<header>`. The names are far too similar.

Change `<title>Ever Hernandez</title>` to something like `<title>LetsJam.com site purpose</title>`. 
`Why?` Titles should be descriptive of the page.

Change this:
```
<div>
  <dt>The purpose of this site is to gather musicians and people alike that are willing
    to learn some skills on how to play togehter. Also, what is like to jam or to have jam
    seessions. Having a place to go on line, also, to find a place to meet offline, to play 
    or jam with people that want to have fun with music.
  </dt>
```
to this:
```
  <p>The purpose of this site is to gather musicians and people alike that are willing
    to learn some skills on how to play togehter. Also, what is like to jam or to have jam
    seessions. Having a place to go on line, also, to find a place to meet offline, to play 
    or jam with people that want to have fun with music.
  </p>
```
_Why?_ The `<div>` serves no purpose there. `<dt>` is only allowed within a definition list `<dl>` container, and you don't have a definition list going on here. 

Do you really want this in the CSS?
```
.video1 {
    margin-left: 1000px;
}
```
It makes that video not show up on some laptops, most tablets and all phones, unless you scroll sideways.

**Comment by palma4k** [comment]
made changes, thank you,
