### ISSUE TITLE
CSS changes for columns

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#8]
https://palma4k.github.io/report/web-creation/bass-history.html tries to cram three columns onto a phone screen. For smaller screens you want fewer columns, so find this:
```
columns {
    column-count: 3;
}
```
and change it to:
```
.columns {
    column-count: 3;
    column-width: 300px;
    column-gap: 40px;
    text-align: left;
    padding: 10px;
}
```
_Why?_ If the column width goes below 300px it drops the number of columns by one. Resize the screen and you'll see it at work.
It puts 40px of space between the columns, making it easier to read.
Left-aligned text is easiest to read when you have a lot of text like this.
The padding puts room between the text and the border, making it easier to read.

**Comment by palma4k** [comment]
made changes, thank you.
