### ISSUE TITLE
HTML changes for History of Bass

### ISSUE THREAD

**Issue by alboss-cascadia** [palma4k/report#9]
In the navigation, capitalize the "h" in "Home" so it matches the rest of the capitalization.

Further down the page, remove this:
```
<br>
<br>
<li><a href="http://www.guitarhistoryfacts.com/guitar-history/timeline-of-guitars/"> History of Bass</a></li>
```
`Why? `You've already got a page heading that says "Timeline of Bass."

**Comment by palma4k** [comment]
Thank you, that was the link of where I had gotten the article, for licenses purposes. but I think I know how to include it. thank you
